spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fruit_greet_mall?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: test
    password: test
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false

      web-stat-filter:
        enabled: false
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 500
          merge-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 25531
      password: test
  security:
    ignore-urls:
      - /swagger-ui/**
      - /swagger-resources/**
      - /webjars/**
      - /doc.html
      - /favicon.ico
      - /v3/api-docs/**
      - /static/**
      - /resources/**
      - /auth/code
      - /login
      - /auth/loginByWeixin
      - /**
  jwt:
    security-key: 3F4428472B4B6250655368566D5971337336763979244226452948404D635166
    expire: 2592000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liyuyouguo.common.entity
  global-config:
    db-config:
      table-prefix: greet_
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liyuyouguo

fruit-shop:
  wx:
    appid: ''
    secret: ''
  express:
    ali:
      app-code: ''
      app-key: ''
      app-secret: ''
  qiniu:
    access-key: ''
    secret-key: ''
    bucket: liyuyouguo
    domain: http://ssdfkeavi.hn-bkt.clouddn.com/